name: golangci-lint
permissions:
  contents: read
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
