name: Tests
permissions:
  contents: read
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Build
        run: go build -v .

      - name: Run Unit Tests with Coverage
        run: |
          # Run only non-acceptance tests (TestProvider and TestProvider_impl) with coverage
          go test -v ./sendgrid/ -run '^TestProvider' -timeout=30s -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: arslanbekov/terraform-provider-sendgrid
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Compile Acceptance Tests
        run: |
          # Compile acceptance tests to ensure they build correctly
          go test -c ./sendgrid/ -o /dev/null

  # Optional: Acceptance tests (only run on master branch)
  acceptance-tests:
    name: Acceptance Tests (Optional)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Run Acceptance Tests with Coverage
        env:
          TF_ACC: "1"
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          if [ -z "$SENDGRID_API_KEY" ]; then
            echo "SENDGRID_API_KEY not set, skipping acceptance tests"
            exit 0
          fi
          go test -v ./sendgrid/ -run '^TestAcc' -timeout=30m -parallel=1 -coverprofile=coverage-acceptance.txt -covermode=atomic

      - name: Upload acceptance test coverage to Codecov
        if: env.SENDGRID_API_KEY != ''
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: arslanbekov/terraform-provider-sendgrid
          flags: acceptancetests
          name: codecov-acceptance
          fail_ci_if_error: false
